apiVersion: v1
kind: Service
metadata:
  name: nyarlathotep
  namespace: shrine
spec:
  type: NodePort
  selector:
    app: nyarlathotep
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
